// First-run setup for a machine (Windows or macOS): creates the files that
// are deliberately NOT in git, then the database. Safe to re-run — it never
// overwrites a file that already exists.
//
//   npm run setup
//
// Creates, if missing:
//   apps/server/.env                         from .env.example, with a fresh random LOCAL_API_KEY
//   apps/web/.env                            matching VITE_API_KEY
//   extension/depop-reader/config.local.js   so the Chrome extension needs no settings
// Then: database migrations, Prisma client, Playwright's Chromium, the
// shared/connector builds, the platform list, and the Claude Code
// SessionStart hook that keeps this machine synced with GitHub.

import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const p = (...parts) => join(root, ...parts);
const say = (msg) => console.log(`[setup] ${msg}`);

// 1. Server .env — keep an existing key, or make a new one for this machine.
const serverEnv = p("apps", "server", ".env");
let apiKey;
if (existsSync(serverEnv)) {
  apiKey = readFileSync(serverEnv, "utf8").match(/^LOCAL_API_KEY="?([^"\r\n]+)"?/m)?.[1];
  say("apps/server/.env exists — kept as is");
} else {
  apiKey = randomBytes(24).toString("hex");
  const example = readFileSync(p("apps", "server", ".env.example"), "utf8");
  writeFileSync(serverEnv, example.replace(/^LOCAL_API_KEY=.*$/m, `LOCAL_API_KEY="${apiKey}"`));
  say("created apps/server/.env with a new LOCAL_API_KEY for this machine");
}
if (!apiKey || apiKey === "change-me-to-a-random-string") {
  console.error("[setup] apps/server/.env has no real LOCAL_API_KEY — set one, then re-run.");
  process.exit(1);
}

// 2. Web .env — must carry the same key.
const webEnv = p("apps", "web", ".env");
if (!existsSync(webEnv)) {
  const example = readFileSync(p("apps", "web", ".env.example"), "utf8");
  writeFileSync(webEnv, example.replace(/^VITE_API_KEY=.*$/m, `VITE_API_KEY=${apiKey}`));
  say("created apps/web/.env");
} else {
  say("apps/web/.env exists — kept as is");
}

// 3. Depop Reader extension config.
const extConfig = p("extension", "depop-reader", "config.local.js");
if (!existsSync(extConfig)) {
  writeFileSync(
    extConfig,
    `// Generated by npm run setup - NOT committed (.gitignore).\nself.MCC_CONFIG = { serverUrl: "http://127.0.0.1:4000", apiKey: "${apiKey}" };\n`,
  );
  say("created extension/depop-reader/config.local.js");
} else {
  say("extension config exists — kept as is");
}

// 4. Database + Prisma client + the browser the real connectors use.
const run = (cmd, cwd = root) => {
  say(`> ${cmd}`);
  execSync(cmd, { cwd, stdio: "inherit" });
};
run("npx prisma migrate deploy", p("apps", "server"));
run("npx prisma generate", p("apps", "server"));
run("npx playwright install chromium");
run("npm run build --workspace=packages/shared");
run("npm run build --workspace=packages/connectors");
// Platform rows (Depop (Live), Facebook (Live)) — upserts only, no sample data.
run("npm run db:seed --workspace=apps/server");

// 5. Claude Code sync hook — every Claude session on this machine starts by
// syncing MCC with GitHub (scripts/sync-check.mjs), so work from the other
// machine is never missing. Merged into the user's Claude settings; set
// MCC_NO_SYNC_HOOK=1 to skip.
if (process.env.MCC_NO_SYNC_HOOK !== "1") installSyncHook();

function installSyncHook() {
  const dir = process.env.CLAUDE_CONFIG_DIR || join(homedir(), ".claude");
  const file = join(dir, "settings.json");
  const command = `node "${join(root, "scripts", "sync-check.mjs").replace(/\\/g, "/")}"`;
  let settings = {};
  if (existsSync(file)) {
    try {
      settings = JSON.parse(readFileSync(file, "utf8"));
    } catch {
      say(`couldn't read ${file} (not valid JSON) — left it alone; add the sync hook by hand (see CLAUDE.md)`);
      return;
    }
  }
  settings.hooks ??= {};
  settings.hooks.SessionStart ??= [];
  const existing = settings.hooks.SessionStart.flatMap((g) => g.hooks ?? []).find((h) => String(h.command ?? "").includes("sync-check.mjs"));
  if (existing?.command === command) {
    say("Claude sync hook already installed");
    return;
  }
  if (existing) existing.command = command; // repo moved — point at this copy
  else {
    settings.hooks.SessionStart.push({
      matcher: "startup|resume",
      hooks: [{ type: "command", command, timeout: 45, statusMessage: "Syncing Marketplace Command Center with GitHub…" }],
    });
  }
  mkdirSync(dir, { recursive: true });
  writeFileSync(file, JSON.stringify(settings, null, 2) + "\n");
  say(`installed the Claude sync hook in ${file} (each Claude session starts by syncing MCC with GitHub)`);
}

say("done. Start MCC with start-dev.cmd (Windows) or start-dev.command (Mac), or `npm run dev`.");
