// First-run setup for a machine (Windows or macOS): creates the files that
// are deliberately NOT in git, then the database. Safe to re-run — it never
// overwrites a file that already exists.
//
//   npm run setup
//
// Creates, if missing:
//   apps/server/.env                         from .env.example, with a fresh random LOCAL_API_KEY
//   apps/web/.env                            matching VITE_API_KEY
//   extension/depop-reader/config.local.js   so the Chrome extension needs no settings
// Then: database migrations, Prisma client, Playwright's Chromium, the
// shared/connector builds, and the platform list.

import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const p = (...parts) => join(root, ...parts);
const say = (msg) => console.log(`[setup] ${msg}`);

// 1. Server .env — keep an existing key, or make a new one for this machine.
const serverEnv = p("apps", "server", ".env");
let apiKey;
if (existsSync(serverEnv)) {
  apiKey = readFileSync(serverEnv, "utf8").match(/^LOCAL_API_KEY="?([^"\r\n]+)"?/m)?.[1];
  say("apps/server/.env exists — kept as is");
} else {
  apiKey = randomBytes(24).toString("hex");
  const example = readFileSync(p("apps", "server", ".env.example"), "utf8");
  writeFileSync(serverEnv, example.replace(/^LOCAL_API_KEY=.*$/m, `LOCAL_API_KEY="${apiKey}"`));
  say("created apps/server/.env with a new LOCAL_API_KEY for this machine");
}
if (!apiKey || apiKey === "change-me-to-a-random-string") {
  console.error("[setup] apps/server/.env has no real LOCAL_API_KEY — set one, then re-run.");
  process.exit(1);
}

// 2. Web .env — must carry the same key.
const webEnv = p("apps", "web", ".env");
if (!existsSync(webEnv)) {
  const example = readFileSync(p("apps", "web", ".env.example"), "utf8");
  writeFileSync(webEnv, example.replace(/^VITE_API_KEY=.*$/m, `VITE_API_KEY=${apiKey}`));
  say("created apps/web/.env");
} else {
  say("apps/web/.env exists — kept as is");
}

// 3. Depop Reader extension config.
const extConfig = p("extension", "depop-reader", "config.local.js");
if (!existsSync(extConfig)) {
  writeFileSync(
    extConfig,
    `// Generated by npm run setup - NOT committed (.gitignore).\nself.MCC_CONFIG = { serverUrl: "http://127.0.0.1:4000", apiKey: "${apiKey}" };\n`,
  );
  say("created extension/depop-reader/config.local.js");
} else {
  say("extension config exists — kept as is");
}

// 4. Database + Prisma client + the browser the real connectors use.
const run = (cmd, cwd = root) => {
  say(`> ${cmd}`);
  execSync(cmd, { cwd, stdio: "inherit" });
};
run("npx prisma migrate deploy", p("apps", "server"));
run("npx prisma generate", p("apps", "server"));
run("npx playwright install chromium");
run("npm run build --workspace=packages/shared");
run("npm run build --workspace=packages/connectors");
// Platform rows (Depop (Live), Facebook (Live)) — upserts only, no sample data.
run("npm run db:seed --workspace=apps/server");

say("done. Start MCC with start-dev.cmd (Windows) or start-dev.command (Mac), or `npm run dev`.");
